apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-hunt-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: product-hunt
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
